### PR TITLE
Shovelling coal into the server...

### PR DESCRIPTION
**Pull request by Sepl9100**
This is the last time we let Gustavo commit ascii porn in the comments.

### CODE REVIEW

**Comment by Olikonsti** [comment]
sus

**Comment by Olikonsti** [comment]
sussy baka

**Comment by Olikonsti** [comment]
mikroweicher bann

**Comment by Olikonsti** [comment]
- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ]

**Comment by Olikonsti** [comment]
__________                                 
         .'----------`.                              
         | .--------. |                             
         | |########| |       __________              
         | |########| |      /__________\             
.--------| `--------' |------|    --=-- |-------------.
|        `----,-.-----'      |o ======  |             | 
|       ______|_|_______     |__________|             | 
|      /  %%%%%%%%%%%%  \                             | 
|     /  %%%%%%%%%%%%%%  \                            | 
|     ^^^^^^^^^^^^^^^^^^^^                            | 
+-----------------------------------------------------+
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Olikonsti** [comment]
ascii art gut

**Comment by Sepl9100** [comment]
Never Run This Commit As Root

**Comment by Sepl9100** [comment]
If it's hacky and you know it clap you hands (clap clap)!

**Comment by Sepl9100** [comment]
Never before had a small typo like this one caused so much damage.

**Comment by Sepl9100** [comment]
It'd be nice if type errors caused the compiler to issue a type error

**Pull request closed without merging**
